import Head from "next/head";
import { SignIn, SignInButton, SignOutButton, UserButton, useUser } from "@clerk/nextjs";
import Link from "next/link";
import { api } from "~/utils/api";
import Image from "next/image";
import { ClerkProvider, SignUp } from "@clerk/nextjs";
import { Component } from "react";
import { log } from "console";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser();
  console.log(user);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">

        <h1 className="text-teal-100">Fantasy Judo - Make the sport personal</h1>
        <div className="flex items-center">
            <a href="#" className="text-sm  text-blue-600 dark:text-blue-500 hover:underline">
              <div>{!user.isSignedIn && <SignInButton />}</div>
              <div>{!!user.isSignedIn && <div></div>}</div>
              {<UserButton/>}
              <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
              </a>
        </div>
      </main>
    </>
  );
}
